In [1]:
#Integer Number
from numpy import random
i = random.randint(10)
print(i)

2


In [2]:
#Float Number
from numpy import random
i = random.rand()
print(i)

0.5204868439289158


In [3]:
from numpy import random
i = random.rand(11)
print(i)

[0.44784663 0.88431529 0.95140867 0.06940791 0.84546285 0.8332576
 0.59386638 0.067354   0.3707899  0.14147455 0.82550064]


In [4]:
#GENERATE 10 RANDOM INTEGERS FROM 0 TO 100
from numpy import random
i = random.randint(100, size=(10))
print(i)

[53 39 24 41 69 15  0 74 98 24]


In [5]:
#Generate 2-D array with 3 rows
from numpy import random
i = random.randint(100, size=(3, 5))
print(i)

[[76 27  2 56 65]
 [91 88 78 33 68]
 [53 23 30 40  8]]


In [6]:
from numpy import random
i = random.randint(100, size=(5, 5))
print(i)

[[ 6 14 59 74 34]
 [63  2 56 61 93]
 [56 62 36 23 74]
 [15 19 34 18 75]
 [70  1  6 87 23]]


In [7]:
from numpy import random
i = random.randint(100, size=(3, 5, 2))
print(i)

[[[73 43]
  [99  7]
  [47 79]
  [99 81]
  [85  0]]

 [[25 66]
  [66 30]
  [21 79]
  [49 79]
  [36 28]]

 [[71 65]
  [ 2 54]
  [53 48]
  [52 43]
  [ 6 99]]]


In [8]:
#Float Number
from numpy import random
i = random.rand(3, 5)
print(i)

[[0.35302785 0.38595254 0.22928122 0.51490825 0.06256965]
 [0.46412639 0.69106147 0.97356848 0.99264795 0.63133365]
 [0.16346354 0.85776124 0.75736702 0.66331018 0.75162786]]


In [10]:
#Choice() Method
from numpy import random
list1 = [10,20,30,40,50,60,70,80,90]
i = random.choice(list1)
print(i)

40


In [11]:
#Choice() - size() Method
from numpy import random
list1 = [10,20,30,40,50,60,70]
i = random.choice(list1, size=(3, 5))
print(i)

[[30 10 10 20 50]
 [40 10 40 40 60]
 [20 40 30 30 60]]


In [9]:
from numpy import random
list1 = [10,20,30,40,50,60,70]
i = random.choice(list1, size=(3, 5, 2))
print(i)

[[[40 10]
  [70 60]
  [40 10]
  [50 10]
  [50 60]]

 [[10 10]
  [40 10]
  [10 70]
  [60 10]
  [70 30]]

 [[10 20]
  [30 30]
  [10 60]
  [10 20]
  [30 30]]]
